// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../prokishi-server/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as registry$0 from "../../../../../shinte/prokishi/registry/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "conn-added": registry$0.Connection;
            "conn-removed": string;
            "request-close": boolean;
            "server-state": main$0.ServerStateEvent;
            "usi-log": registry$0.USILogEvent;
        }
    }
}
