// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Connection {
    /**
     * Creates a new Connection instance.
     * @param {Partial<Connection>} [$$source = {}] - The source object to create the Connection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("engineId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engineId"] = "";
        }
        if (!("engineName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engineName"] = "";
        }
        if (!("enginePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["enginePath"] = "";
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["connectedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Connection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection(/** @type {Partial<Connection>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const Direction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * client → engine
     */
    DirSend: 0,

    /**
     * engine → client
     */
    DirRecv: 1,
};

export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {Direction}
             */
            this["dir"] = Direction.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

export class USILogEvent {
    /**
     * Creates a new USILogEvent instance.
     * @param {Partial<USILogEvent>} [$$source = {}] - The source object to create the USILogEvent.
     */
    constructor($$source = {}) {
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connId"] = "";
        }
        if (!("entry" in $$source)) {
            /**
             * @member
             * @type {LogEntry}
             */
            this["entry"] = (new LogEntry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new USILogEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {USILogEvent}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField1_0($$parsedSource["entry"]);
        }
        return new USILogEvent(/** @type {Partial<USILogEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = LogEntry.createFrom;
