// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Connection {
    "id": string;
    "engineId": string;
    "engineName": string;
    "enginePath": string;
    "connectedAt": time$0.Time;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("engineId" in $$source)) {
            this["engineId"] = "";
        }
        if (!("engineName" in $$source)) {
            this["engineName"] = "";
        }
        if (!("enginePath" in $$source)) {
            this["enginePath"] = "";
        }
        if (!("connectedAt" in $$source)) {
            this["connectedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export enum Direction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * client → engine
     */
    DirSend = 0,

    /**
     * engine → client
     */
    DirRecv = 1,
};

export class LogEntry {
    "timestamp": time$0.Time;
    "dir": Direction;
    "message": string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("dir" in $$source)) {
            this["dir"] = Direction.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class USILogEvent {
    "connId": string;
    "entry": LogEntry;

    /** Creates a new USILogEvent instance. */
    constructor($$source: Partial<USILogEvent> = {}) {
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("entry" in $$source)) {
            this["entry"] = (new LogEntry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new USILogEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): USILogEvent {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField1_0($$parsedSource["entry"]);
        }
        return new USILogEvent($$parsedSource as Partial<USILogEvent>);
    }
}

// Private type creation functions
const $$createType0 = LogEntry.createFrom;
