// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCode(code) {
    return $Call.ByID(1773064644, code);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEngine(id) {
    return $Call.ByID(1226345227, id);
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function DisableCode(code) {
    return $Call.ByID(3472157279, code);
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function EnableCode(code) {
    return $Call.ByID(100507728, code);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GenerateCode() {
    return $Call.ByID(1460603676);
}

/**
 * @returns {$CancellablePromise<$models.CodeItem[]>}
 */
export function ListCodes() {
    return $Call.ByID(25729496).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.EngineItem[]>}
 */
export function ListEngines() {
    return $Call.ByID(2160820709).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function RegisterCode(code) {
    return $Call.ByID(2081311114, code);
}

/**
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function RegisterEngine(path, name) {
    return $Call.ByID(557474797, path, name);
}

/**
 * SaveClientConfig はクライアント設定ファイル (prokishi.ini) をファイル保存ダイアログで書き出す。
 * @param {string} host
 * @param {number} port
 * @param {string} code
 * @param {string} engineId
 * @param {string} logLevel
 * @returns {$CancellablePromise<void>}
 */
export function SaveClientConfig(host, port, code, engineId, logLevel) {
    return $Call.ByID(266601238, host, port, code, engineId, logLevel);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectEnginePath() {
    return $Call.ByID(2300570047);
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateEngineName(id, name) {
    return $Call.ByID(1687481118, id, name);
}

// Private type creation functions
const $$createType0 = $models.CodeItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.EngineItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
