// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(1773064644, code);
}

export function DeleteEngine(id: string): $CancellablePromise<void> {
    return $Call.ByID(1226345227, id);
}

export function GenerateCode(): $CancellablePromise<string> {
    return $Call.ByID(1460603676);
}

export function ListCodes(): $CancellablePromise<$models.CodeItem[]> {
    return $Call.ByID(25729496).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListEngines(): $CancellablePromise<$models.EngineItem[]> {
    return $Call.ByID(2160820709).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RegisterCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(2081311114, code);
}

export function RegisterEngine(path: string): $CancellablePromise<string> {
    return $Call.ByID(557474797, path);
}

export function SelectEnginePath(): $CancellablePromise<string> {
    return $Call.ByID(2300570047);
}

// Private type creation functions
const $$createType0 = $models.CodeItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.EngineItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
