// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(1773064644, code);
}

export function DeleteEngine(id: string): $CancellablePromise<void> {
    return $Call.ByID(1226345227, id);
}

export function DisableCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(3472157279, code);
}

export function EnableCode(code: string): $CancellablePromise<void> {
    return $Call.ByID(100507728, code);
}

export function GenerateCode(name: string): $CancellablePromise<string> {
    return $Call.ByID(1460603676, name);
}

export function ListCodes(): $CancellablePromise<$models.CodeItem[]> {
    return $Call.ByID(25729496).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListEngines(): $CancellablePromise<$models.EngineItem[]> {
    return $Call.ByID(2160820709).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RegisterCode(code: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2081311114, code, name);
}

export function RegisterEngine(path: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(557474797, path, name);
}

/**
 * SaveClientConfig はクライアント設定ファイル (prokishi.ini) をファイル保存ダイアログで書き出す。
 */
export function SaveClientConfig(host: string, port: number, code: string, engineId: string, logLevel: string): $CancellablePromise<void> {
    return $Call.ByID(266601238, host, port, code, engineId, logLevel);
}

export function SelectEnginePath(): $CancellablePromise<string> {
    return $Call.ByID(2300570047);
}

export function UpdateCodeName(code: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(999974465, code, name);
}

export function UpdateEngineName(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1687481118, id, name);
}

// Private type creation functions
const $$createType0 = $models.CodeItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.EngineItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
