// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLogs(id: string): $CancellablePromise<$models.LogEntryItem[]> {
    return $Call.ByID(2206052633, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListConnections(): $CancellablePromise<$models.ConnectionInfo[]> {
    return $Call.ByID(4265673495).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LogEntryItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ConnectionInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
