// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CodeItem {
    /**
     * Creates a new CodeItem instance.
     * @param {Partial<CodeItem>} [$$source = {}] - The source object to create the CodeItem.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["used"] = "";
        }
        if (!("disabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodeItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeItem(/** @type {Partial<CodeItem>} */($$parsedSource));
    }
}

export class ConnectionInfo {
    /**
     * Creates a new ConnectionInfo instance.
     * @param {Partial<ConnectionInfo>} [$$source = {}] - The source object to create the ConnectionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("engineId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engineId"] = "";
        }
        if (!("engineName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engineName"] = "";
        }
        if (!("enginePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["enginePath"] = "";
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connectedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo(/** @type {Partial<ConnectionInfo>} */($$parsedSource));
    }
}

export class EngineItem {
    /**
     * Creates a new EngineItem instance.
     * @param {Partial<EngineItem>} [$$source = {}] - The source object to create the EngineItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EngineItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineItem(/** @type {Partial<EngineItem>} */($$parsedSource));
    }
}

export class LogEntryItem {
    /**
     * Creates a new LogEntryItem instance.
     * @param {Partial<LogEntryItem>} [$$source = {}] - The source object to create the LogEntryItem.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("dir" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dir"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntryItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryItem(/** @type {Partial<LogEntryItem>} */($$parsedSource));
    }
}

export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}

export class ServerStateEvent {
    /**
     * Creates a new ServerStateEvent instance.
     * @param {Partial<ServerStateEvent>} [$$source = {}] - The source object to create the ServerStateEvent.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStateEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerStateEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStateEvent(/** @type {Partial<ServerStateEvent>} */($$parsedSource));
    }
}
