// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CodeItem {
    "code": string;
    "name": string;
    "created": string;
    "used": string;
    "disabled": boolean;

    /** Creates a new CodeItem instance. */
    constructor($$source: Partial<CodeItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("used" in $$source)) {
            this["used"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeItem($$parsedSource as Partial<CodeItem>);
    }
}

export class ConnectionInfo {
    "id": string;
    "engineId": string;
    "engineName": string;
    "enginePath": string;
    "connectedAt": string;

    /** Creates a new ConnectionInfo instance. */
    constructor($$source: Partial<ConnectionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("engineId" in $$source)) {
            this["engineId"] = "";
        }
        if (!("engineName" in $$source)) {
            this["engineName"] = "";
        }
        if (!("enginePath" in $$source)) {
            this["enginePath"] = "";
        }
        if (!("connectedAt" in $$source)) {
            this["connectedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo($$parsedSource as Partial<ConnectionInfo>);
    }
}

export class CpuInfo {
    "total": number;
    "perCpu": number[];
    "modelName": string;
    "cores": number;

    /** Creates a new CpuInfo instance. */
    constructor($$source: Partial<CpuInfo> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("perCpu" in $$source)) {
            this["perCpu"] = [];
        }
        if (!("modelName" in $$source)) {
            this["modelName"] = "";
        }
        if (!("cores" in $$source)) {
            this["cores"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CpuInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CpuInfo {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perCpu" in $$parsedSource) {
            $$parsedSource["perCpu"] = $$createField1_0($$parsedSource["perCpu"]);
        }
        return new CpuInfo($$parsedSource as Partial<CpuInfo>);
    }
}

export class EngineItem {
    "id": string;
    "name": string;
    "path": string;
    "created": string;

    /** Creates a new EngineItem instance. */
    constructor($$source: Partial<EngineItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineItem($$parsedSource as Partial<EngineItem>);
    }
}

export class LogEntryItem {
    "timestamp": string;
    "dir": number;
    "message": string;

    /** Creates a new LogEntryItem instance. */
    constructor($$source: Partial<LogEntryItem> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntryItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryItem($$parsedSource as Partial<LogEntryItem>);
    }
}

export class ProcessCpuInfo {
    "connId": string;
    "engineName": string;
    "pid": number;
    "cpuPercent": number;

    /** Creates a new ProcessCpuInfo instance. */
    constructor($$source: Partial<ProcessCpuInfo> = {}) {
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("engineName" in $$source)) {
            this["engineName"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessCpuInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessCpuInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessCpuInfo($$parsedSource as Partial<ProcessCpuInfo>);
    }
}

export class ServerConfig {
    "host": string;
    "port": number;
    "autoStart": boolean;
    "useAuth": boolean;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("useAuth" in $$source)) {
            this["useAuth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

export class ServerStateEvent {
    "running": boolean;
    "url": string;

    /** Creates a new ServerStateEvent instance. */
    constructor($$source: Partial<ServerStateEvent> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStateEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStateEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStateEvent($$parsedSource as Partial<ServerStateEvent>);
    }
}

export class SystemInfo {
    "cpu": CpuInfo | null;
    "processes": ProcessCpuInfo[];

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("cpu" in $$source)) {
            this["cpu"] = null;
        }
        if (!("processes" in $$source)) {
            this["processes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cpu" in $$parsedSource) {
            $$parsedSource["cpu"] = $$createField0_0($$parsedSource["cpu"]);
        }
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField1_0($$parsedSource["processes"]);
        }
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CpuInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ProcessCpuInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
