// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CodeItem {
    "code": string;
    "name": string;
    "created": string;
    "used": string;
    "disabled": boolean;

    /** Creates a new CodeItem instance. */
    constructor($$source: Partial<CodeItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("used" in $$source)) {
            this["used"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeItem($$parsedSource as Partial<CodeItem>);
    }
}

export class ConnectionInfo {
    "id": string;
    "engineId": string;
    "engineName": string;
    "enginePath": string;
    "connectedAt": string;

    /** Creates a new ConnectionInfo instance. */
    constructor($$source: Partial<ConnectionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("engineId" in $$source)) {
            this["engineId"] = "";
        }
        if (!("engineName" in $$source)) {
            this["engineName"] = "";
        }
        if (!("enginePath" in $$source)) {
            this["enginePath"] = "";
        }
        if (!("connectedAt" in $$source)) {
            this["connectedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo($$parsedSource as Partial<ConnectionInfo>);
    }
}

export class EngineItem {
    "id": string;
    "name": string;
    "path": string;
    "created": string;

    /** Creates a new EngineItem instance. */
    constructor($$source: Partial<EngineItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineItem($$parsedSource as Partial<EngineItem>);
    }
}

export class LogEntryItem {
    "timestamp": string;
    "dir": number;
    "message": string;

    /** Creates a new LogEntryItem instance. */
    constructor($$source: Partial<LogEntryItem> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntryItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntryItem($$parsedSource as Partial<LogEntryItem>);
    }
}

export class ServerConfig {
    "host": string;
    "port": number;
    "autoStart": boolean;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

export class ServerStateEvent {
    "running": boolean;
    "url": string;

    /** Creates a new ServerStateEvent instance. */
    constructor($$source: Partial<ServerStateEvent> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStateEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStateEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStateEvent($$parsedSource as Partial<ServerStateEvent>);
    }
}
