// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CodeItem {
    "code": string;
    "created": string;
    "used": string;

    /** Creates a new CodeItem instance. */
    constructor($$source: Partial<CodeItem> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("used" in $$source)) {
            this["used"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeItem($$parsedSource as Partial<CodeItem>);
    }
}

export class EngineItem {
    "id": string;
    "path": string;
    "created": string;

    /** Creates a new EngineItem instance. */
    constructor($$source: Partial<EngineItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineItem instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineItem($$parsedSource as Partial<EngineItem>);
    }
}
