// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig はファイルから設定を読む。ファイルがなければデフォルト値を返す。
 */
export function GetConfig(): $CancellablePromise<$models.ServerConfig> {
    return $Call.ByID(118542436).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLocalIPs はループバックを除く IPv4 アドレス一覧を返す。
 */
export function GetLocalIPs(): $CancellablePromise<string[]> {
    return $Call.ByID(4208826961).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetState は現在の状態をまとめて返す（フロントエンド初期化用）。
 */
export function GetState(): $CancellablePromise<$models.ServerStateEvent> {
    return $Call.ByID(3232216287).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetURL(): $CancellablePromise<string> {
    return $Call.ByID(4251959123);
}

/**
 * InitConfig はファイルが存在しない場合だけ初期値を書く（初回起動時のフラグ移行）。
 */
export function InitConfig(host: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(1617196898, host, port);
}

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1115397425);
}

/**
 * SaveConfig は設定をファイルに書く。
 */
export function SaveConfig(cfg: $models.ServerConfig): $CancellablePromise<void> {
    return $Call.ByID(1985109641, cfg);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1602833774);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(934708918);
}

// Private type creation functions
const $$createType0 = $models.ServerConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.ServerStateEvent.createFrom;
