// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig はファイルから設定を読む。ファイルがなければデフォルト値を返す。
 * @returns {$CancellablePromise<$models.ServerConfig>}
 */
export function GetConfig() {
    return $Call.ByID(118542436).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetState は現在の状態をまとめて返す（フロントエンド初期化用）。
 * @returns {$CancellablePromise<$models.ServerStateEvent>}
 */
export function GetState() {
    return $Call.ByID(3232216287).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetURL() {
    return $Call.ByID(4251959123);
}

/**
 * InitConfig はファイルが存在しない場合だけ初期値を書く（初回起動時のフラグ移行）。
 * @param {string} host
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function InitConfig(host, port) {
    return $Call.ByID(1617196898, host, port);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning() {
    return $Call.ByID(1115397425);
}

/**
 * SaveConfig は設定をファイルに書く。
 * @param {$models.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(1985109641, cfg);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(1602833774);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(934708918);
}

// Private type creation functions
const $$createType0 = $models.ServerConfig.createFrom;
const $$createType1 = $models.ServerStateEvent.createFrom;
