// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ShutdownAndQuit はフロントエンドの確認ダイアログで承認された後に呼ばれる。
 * サーバを停止してアプリケーションを終了する。
 */
export function ShutdownAndQuit(): $CancellablePromise<void> {
    return $Call.ByID(190060143);
}
